project:
  type: website
  output-dir: docs
website:
  title: "Cassidy Cobb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Background
      - href: courses.qmd
        text: Relevant Courses
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

